url: 'http://localhost:5000/wps'
allowedinputpaths:
  - './static/'
  - 'd:\Maps'
  - 'd:\MRR'
#default_mimetype: 'application/json'
#json_indent: -1
json_indent: 2

root: 'd:\Maps'

dtm_color_palette: './static/data/color_files/color_file_1.txt'

dtm_geo: 'd:\Maps\w84geo\dtm_SRTM1_hgt_ndv0.cog.tif.new.cog.tif'

dtm_utm: 'd:\maps\srtm3\utm\*.tif'
