say_hello:
  name: "default-config"

ls:
  dir: '{{ root }}'
  pattern: '*.tif'

tester:
  r: '{{ dtm_geo }}'
  name: 'Tester'

ras_val:
  r: '{{ dtm_geo }}'

geod_profile:
  r: '{{ dtm_geo }}'

crop_color:
  r: '{{ dtm_geo }}'
  of: 'czml'
#  color_palette: '{{ dtm_color_palette }}'

viewshed:
  r: '{{ dtm_utm }}'
  of: 'czml'
  in_crs: '0'
  out_crs: '0'
  backend: 'talos'

  fill_center: False
  power_diff: 0
  profile_extension: True

los:
  of: 'json'
  r: '{{ dtm_geo }}'
  in_crs: '0'
  out_crs: '0'
  backend: 'radio'

  fill_center: False
  power_diff: 0
  profile_extension: True
